### ISSUE TITLE
Create a Wikia Wiki and Check whether this Wiki is Extracted

### ISSUE THREAD

**Issue by janothan** [WikiaTeamProject/ExtractionFromWikia#10]

**Comment by AlexandraHofmann** [comment]
created wiki: http://de.bibiundtina.wikia.com/

found out that a wiki created in english language does not have a prefix, like "de" in the URL
i.e. http://harrypotter.wikia.com

**Comment by AlexandraHofmann** [comment]
wikia ID of created wiki: 1546408

**Comment by AlexandraHofmann** [comment]
find ID in html --> wgCityId
