### ISSUE TITLE
Write More Sophisticated Statistics Methods

### ISSUE THREAD

**Issue by janothan** [WikiaTeamProject/ExtractionFromWikia#17]
- distribution of size by articles -> check for power law distribution
- distribution of articles by language
- try to get the file size

**Comment by AlexandraHofmann** [comment]
file size extracted and saved in an extra file "wikiaDumpsSizes.csv" in specified directory

**Comment by AlexandraHofmann** [comment]
use R ?

**Comment by AlexandraHofmann** [comment]
done in excel
