### ISSUE TITLE
find out cause of HTTP error

### ISSUE THREAD

**Issue by AlexandraHofmann** [WikiaTeamProject/ExtractionFromWikia#26]
- find out when HTTP error happens when running wikiaStatisticsApplication

**Comment by janothan** [comment]
To me, it looks like the HTTP error occurs mainly (only?) when wikis were deleted. This needs to be verified.
If this would be the case, I think we can close this bug, because this would not be very problematic.

**Comment by janothan** [comment]
I cannot replicate the problem.
