### ISSUE TITLE
Use API to get number of all wikis

### ISSUE THREAD

**Issue by janothan** [WikiaTeamProject/ExtractionFromWikia#4]
- look into API
- find appropriate method (at the moment: "Get Information About Wikis")
- Write loops that will query all wikis with ID 1 to 1 million
- count the number of IDs that get returned

API Link: http://api.wikia.com/wiki/Fandom_API_Wiki 

If there are problems with the Fandom API, evaluate also the other 2 APIs:
- MediaWiki API - Since Fandom wikis are built on top of MediaWiki, the MediaWiki API can be used to access most of the data on our websites.
- LyricWiki API - Provides access to LyricWiki.

**Comment by AlexandraHofmann** [comment]
method "Get Information About Wikis" used to retrieve wiki information
ID 1 to 3 million were queried
about 370000 wikis with information retrieved and saved as csv
