### ISSUE TITLE
Get Statistics

### ISSUE THREAD

**Issue by janothan** [WikiaTeamProject/ExtractionFromWikia#5]
Do that after: #4

Get Statistics
- number of languages
- pagecount (how many pages exist in that particular wiki?)
     - todo: what is the difference between articles and pages (somehow used interchangeably)
- categories 
     - main category called "hubs": Videogames, Entertainment or Lifestyle
     - topics

**Comment by AlexandraHofmann** [comment]
duplicate of #8 
therefore closed
