### ISSUE TITLE
Make Sense of the different File Structures

### ISSUE THREAD

**Issue by janothan** [WikiaTeamProject/ExtractionFromWikia#54]
Currently , there are 3 different file structures:
1) Download
2) Pre-Extraction (format required to use the dbpedia-extractor)
3) Final Structure

Transformation from step 1 to step 2 is already completed by Sam.

In the config file, there should be only ONE parameter for a Root Folder.

Root (we only specify this folder)
--- DownloadedWikis (step 1)
--- DbPediaExtractionFormat (step 2)
--- PostProcessedWikis (step 3)

**Comment by AlexandraHofmann** [comment]
also included another folder in root where the statistics are saved
--wikiStatistics
