### ISSUE TITLE
Postprocess Labels

### ISSUE THREAD

**Issue by janothan** [WikiaTeamProject/ExtractionFromWikia#64]
#67 Restructure the labels file:

Example:

labels.ttl
```
<Bran> <label> "Bran"
<Brandon> <label> "Brandon"
<Brandon Stark> <label> "Brandon Stark"
```

redirect.ttl
`<Bran> <sameAs> <Brandon>`
`<Brandon> <sameAs> <Brandon Stark>`

new labels.ttl
```
<Brandon Stark> <skos: preferred_label> "Brandon Stark"
<Brandon Stark> <skos:alternative_label> "Brandon"
<Brandon Stark> <skos:alternative_label> "Bran"

```

Look into the SKOS framework to get correct tags.

**Comment by AlexandraHofmann** [comment]
using 
- skos:prefLabel 
- skos:altLabel
