### ISSUE TITLE
Create a "SingleProcess" Class

### ISSUE THREAD

**Issue by janothan** [WikiaTeamProject/ExtractionFromWikia#70]
- create a class that does everything from the download to the extraction & mapping.
- how to use the class and what to make sure (prerequisites) should go into the readme of the project

Note:
- executing the class should be very safe, i.e., the execution should not fail catastrophically but gracefully
- before starting everything, the class should make sure that all directories and files exist. If this is not the case, specific instructions should be provided on what is to do in order to run everything. For example: if the directory "pageids" or "redirects" in the rootDirectory do not exist, there should be an output that the directories need to be created and that there must be ttl files in them.

**Comment by AlexandraHofmann** [comment]
- write a test for the class with 10 wikis
- include checkPrerequisites() method of each subapplication
