### ISSUE TITLE
Use Correct samAs Notation

### ISSUE THREAD

**Issue by janothan** [WikiaTeamProject/ExtractionFromWikia#81]

**Comment by janothan** [comment]
The properties for the mapping should be as follows:
for class mappings:
<http://www.w3.org/2002/07/owl#equivalentClass>
for property mappings
<http://www.w3.org/2002/07/owl#equivalentProperty>
for resource mappings:
<http://www.w3.org/2002/07/owl#sameAs>

**Comment by AlexandraHofmann** [comment]
should be fixed
